### PR TITLE
[FIX] Ignore custom languages during update of languages

### LINKED ISSUE #28470: Autoupgrade- Error when upgrade if new specific language is added
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Error when upgrade if new specifif language is added.
image
image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to Localization > languags> Add new language
2. Fill all required data with  fields of your choice 
3. Upgrade to major version
4. see error

### PrestaShop version(s) where the bug happened

1.7.6.5/ 1.7.7.8/ 1.7.6.7

### PHP version(s) where the bug happened

7.1, 7.2

### If your bug is related to a module, specify its name and its version

autoupgrade version 4.14.0 and  4.14.1

### PR DESCRIPTION
**Pull request by ga-devfront**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix the issue then a merchant try an update with custom lang.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | fix https://github.com/PrestaShop/PrestaShop/issues/28470
| Sponsor company   | @PrestaShopCorp
| How to test?      | see internal ticket

### CODE REVIEW

**Review by tblivet — DISMISSED** [review]

**Review by Quetzacoalt91 — DISMISSED** [review]

File: classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php [hunk 1]
```diff
@@ -65,7 +65,7 @@ protected function upgradeLanguage($lang): void
     {
         $isoCode = $lang['iso_code'];
 
-        if (!\Validate::isLangIsoCode($isoCode)) {
+        if (!\Validate::isLangIsoCode($isoCode) || !\Language::getLangDetails($isoCode)) {
             $this->logger->debug($this->container->getTranslator()->trans('%lang% is not a valid iso code, skipping', ['%lang%' => $isoCode]));
 
             return;
```
Comment (Quetzacoalt91) [inline classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php:71]: Could be interesting to move this part is the caller, because we won't get any notice in this case when we upgrade to a PrestaShop 1.7

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @ga-devfront 

Thank you for your PR, I tested it and it seems to works as you can see : 

https://github.com/user-attachments/assets/604753eb-5188-4624-a503-c035d8ee0d9a

Tested from : 
1.7.6.5 to 8.2.1 
8.0.2 to 8.2.1 
1.7.6.5 to 8.0.2 

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you
