### PR TITLE
Use Distribution API endpoints to get updates infos

### LINKED ISSUE #31791: The autoupgrade module make a call to prestashop.com API
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In https://github.com/PrestaShop/autoupgrade/blob/dev/classes/Upgrader.php#L41-L42, we see that calls are made to api.prestashop.com

### Expected behavior

Following this EPIC #28771, that should target a `prestashop-project.org` endpoint.

That should be configurable.

### Steps to reproduce

N/A

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ga-devfront**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | In view of the deprecation of `channel.xml` this PR aims to use the new endpoints available on distribution API.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/31791
| Sponsor company   | @PrestaShopCorp
| How to test?      | Check related ticket

### CODE REVIEW

File: classes/Models/PrestashopRelease.php [hunk 1]
```diff
@@ -39,6 +39,8 @@ class PrestashopRelease
     private $releaseNoteUrl;
     /** @var 'rc'|'beta'|'stable' */
     private $stability;
+    /** @var 'open_source'|'classic' */
+    private $distribution;
```
Comment (M0rgan01) [inline classes/Models/PrestashopRelease.php]: It might be worth adding "distribution_version" too, right?

File: classes/Models/PrestashopRelease.php [hunk 2]
```diff
@@ -58,6 +61,8 @@ public function __construct(
         $this->zipMd5 = $zipMd5;
         $this->releaseNoteUrl = $releaseNoteUrl;
         $this->stability = $stability;
+        $this->releaseNoteUrl = $releaseNoteUrl;
```
Comment (M0rgan01) [inline classes/Models/PrestashopRelease.php]: Already exist L62

File: classes/Services/DistributionApiService.php [hunk 3]
```diff
@@ -71,26 +83,49 @@ public function getPhpVersionRequirements(string $targetVersion): array
...
+        }
+
+        return $releases;
+    }
+
+    /**
+     * @return AutoupgradeRelease[]
+     *
+     * @throws DistributionApiException
+     */
```
Comment (M0rgan01) [inline classes/Services/DistributionApiService.php]:
```suggestion
    /**
     * @throws DistributionApiException
     *
     * @return AutoupgradeRelease[]
     */
```

File: classes/Services/PhpVersionResolverService.php [hunk 4]
```diff
@@ -125,27 +106,22 @@ public function getPrestashopDestinationRelease(int $currentPhpVersionId): ?Pres
...
-        if (empty($releasesFromChannelFile)) {
-            throw new UpgradeException('Unable to retrieve latest 1.7 release of Prestashop.');
-        }
+        $releases = $this->distributionApiService->getReleases();
 
-        if ($currentPhpVersion < 70200) {
-            $release = $releasesFromChannelFile['1.7'];
+        if (empty($releases)) {
+            throw new UpgradeException('Unable to retrieve releases of Prestashop.');
+        }
```
Comment (M0rgan01) [inline classes/Services/PhpVersionResolverService.php]: Are there scenarios where the API returns nothing? If this is the case, shouldn't this be done on the distribution API service and an exception raised higher?

File: classes/Services/PhpVersionResolverService.php [hunk 5]
```diff
@@ -125,27 +106,22 @@ public function getPrestashopDestinationRelease(int $currentPhpVersionId): ?Pres
...
-            // current version is superior or equal
-            if (version_compare($this->currentPsVersion, $release->getVersion(), '>=')) {
-                return null;
-            }
+        $autoupgradeCompatibilities = $this->distributionApiService->getAutoupgradeReleases();
 
-            return $release;
+        if (empty($autoupgradeCompatibilities)) {
+            throw new UpgradeException('Unable to retrieve autoupgrade compatibilities.');
         }
```
Comment (M0rgan01) [inline classes/Services/PhpVersionResolverService.php]: Are there scenarios where the API returns nothing? If this is the case, shouldn't this be done on the distribution API service and an exception raised higher?

File: classes/Services/PhpVersionResolverService.php [hunk 6]
```diff
@@ -125,27 +106,22 @@ public function getPrestashopDestinationRelease(int $currentPhpVersionId): ?Pres
...
 
         $validReleases = [];
 
-        foreach ($this->distributionApiService->getReleases() as $release) {
-            if ($release->getStability() !== 'stable') {
+        foreach ($releases as $release) {
+            if ($release->getStability() !== 'stable' || $release->getZipDownloadUrl() === null || $release->getXmlDownloadUrl() === null) {
                 continue;
             }
```
Comment (M0rgan01) [inline classes/Services/PhpVersionResolverService.php]: > || $release->getZipDownloadUrl() === null || $release->getXmlDownloadUrl() === null

This information is important, we could possibly log it, right?

File: classes/Services/PhpVersionResolverService.php [hunk 7]
```diff
@@ -154,6 +130,22 @@ public function getPrestashopDestinationRelease(int $currentPhpVersionId): ?Pres
...
 
+            // add check compat with autoupgrade module
+
+            $autoupgradeSupportVersion = false;
+
+            foreach ($autoupgradeCompatibilities as $autoupgradeCompatibility) {
+                if ($autoupgradeCompatibility->getPrestashopMaxVersion() >= $release->getVersion() && $autoupgradeCompatibility->getPrestashopMinVersion() <= $release->getVersion()) {
```
Comment (M0rgan01) [inline classes/Services/PhpVersionResolverService.php]: Here we are comparing strings. It might be better to use `version_compare`

File: classes/Upgrader.php [hunk 8]
```diff
@@ -121,17 +126,30 @@ public function getDestinationVersion(): ?string
...
      * @throws UpgradeException
      */
     public function getLatestModuleVersion(): string
     {
-        $channelFile = $this->fileLoader->getXmlChannel();
+        $autoupgradeReleases = $this->distributionApiService->getAutoupgradeReleases();
+
+        if (empty($autoupgradeReleases)) {
+            throw new UpgradeException($this->translator->trans('Unable to retrieve autoupgrade releases.'));
+        }
```
Comment (M0rgan01) [inline classes/Upgrader.php]: This should be managed in the service

File: classes/Upgrader.php [hunk 9]
```diff
@@ -121,17 +126,30 @@ public function getDestinationVersion(): ?string
...
+
+        $destinationVersion = $this->getDestinationVersion();
+
+        $eligibleAutoupgradeReleases = array_filter($autoupgradeReleases, function ($autoupgradeRelease) use ($destinationVersion) {
+            return $autoupgradeRelease->getPrestashopMinVersion() <= $destinationVersion && $autoupgradeRelease->getPrestashopMaxVersion() >= $destinationVersion;
```
Comment (M0rgan01) [inline classes/Upgrader.php:143]: Here we are comparing strings. It might be better to use version_compare

**Review by M0rgan01 — DISMISSED** [review]

File: classes/Upgrader.php [hunk 10]
```diff
@@ -121,17 +126,30 @@ public function getDestinationVersion(): ?string
...
+        });
+
+        $autoupgradeRelease = reset($eligibleAutoupgradeReleases);
 
-        if (empty($channelFile)) {
-            throw new UpgradeException($this->translator->trans('Unable to retrieve channel.xml.'));
+        if ($autoupgradeRelease === false) {
+            throw new UpgradeException($this->translator->trans('Unable to retrieve autoupgrade recommended release.'));
```
Comment (Quetzacoalt91) [inline classes/Upgrader.php]:
```suggestion
            throw new UpgradeException($this->translator->trans('There is no recommended version of Update Assistant for PrestaShop %version%.', ['%version%' => $destinationVersion]));
```

File: classes/Upgrader.php [hunk 11]
```diff
@@ -121,17 +126,30 @@ public function getDestinationVersion(): ?string
...
+     * @throws DistributionApiException
      * @throws UpgradeException
      */
     public function getLatestModuleVersion(): string
     {
-        $channelFile = $this->fileLoader->getXmlChannel();
+        $autoupgradeReleases = $this->distributionApiService->getAutoupgradeCompatibilities();
+
+        if (empty($autoupgradeReleases)) {
+            throw new UpgradeException($this->translator->trans('Unable to retrieve autoupgrade releases.'));
```
Comment (Quetzacoalt91) [inline classes/Upgrader.php]:
```suggestion
            throw new UpgradeException($this->translator->trans('Unable to retrieve the recommended releases of Update Assistant.'));
```

File: classes/Services/PhpVersionResolverService.php [hunk 12]
```diff
@@ -125,35 +104,37 @@ public function getPrestashopDestinationRelease(int $currentPhpVersionId): ?Pres
...
-                return null;
+                continue;
             }
 
-            return $release;
-        }
+            // add check compat with autoupgrade module
 
-        $validReleases = [];
+            $autoupgradeSupportVersion = false;
```
Comment (Quetzacoalt91) [inline classes/Services/PhpVersionResolverService.php]:
```suggestion
            $isEligibleForUpdate = false;
```

File: classes/Upgrader.php (hunk 10 above)
Comment (Quetzacoalt91) [reply classes/Upgrader.php]: This needs to be checked: I'm wondering if upgrades to PrestaShop v9 will trigger an HTTP 500 during the requirements checks, as it does not exist on the `/autoupgrade` endpoint yet.

**Comment by ingridusta** [comment]
Hello @ga-devfront, 

QA Note detected : 

**Steps to reproduce :**
Step 1: Install fresh new shop 1.7.4.2-7.1-fpm-alpine-nginx PHP version: 7.1.33
Step 2: Install Update assistant module
Step 3: Go on the Update assistant module
Step 4: Select "Update your store" choice
Step 5: Click on the CTA "Get Started"
Step 6: Select the more recent version is available (here PrestaShop 1.7.8.11)

**Expected results :**
Step 1: Shop available
Step 2: Update assistant module installed
Step 3: Update assistant module's LP page displayed
Step 4: "Update your store" choice selected
Step 5: Version choice page displayed
Step 6: "Checking requirements..." is on going and after a moment, the results are displayed

**Obtained results :**
Step 1: Shop available
Step 2: Update assistant module installed
Step 3: Update assistant module's LP page displayed
Step 4: "Update your store" choice selected
Step 5: Version choice page displayed
Step 6: **ERROR 500 ajax-upgradetab.php?route=update-step-version-choice-save-form**

Capture d’écran 2025-05-02 à 11 28 33

https://github.com/user-attachments/assets/2f0a647f-a8d7-40b2-a73a-07bb2e0ae327

**Review by ingridusta — CHANGES_REQUESTED** [review]
Hi @ga-devfront, 

QA note detected : When the user tries to update to v9 (when the PS v not supported https://api.prestashop-project.org/autoupgrade) with local archive, an error 500 pops at the end of the requierements checks instead of a warning.

**How to reproduce :** 
Step 1: Add a .zip and .xml of PS v9 in the shop's files (var/www/html/autoupgrade/download)
Step 2: On the module, select the choice "Update your store"
Step 3: Click on the CTA "Get started"
Step 4: Click on the choice "Local archive"
Step 5: Select "Archive to use" and "XML file to use"

**Expected results :** 
Step 1: .zip and .xml of PS v9 added
Step 2: Choice "Update your store" selected + CTA "Get started" accessible
Step 3: Version choice page displayed
Step 4: "Archive to use" and "XML file to use" dropdown menus are displayed
Step 5: "Checking requirements..." is loading, after a moment warning(s) are displayed

**Obtained results :** 
Step 1: .zip and .xml of PS v9 added
Step 2: Choice "Update your store" selected + CTA "Get started" accessible
Step 3: Version choice page displayed
Step 4: "Archive to use" and "XML file to use" dropdown menus are displayed
Step 5: "Checking requirements..." is loading, request ajax-upgradetab.php?route=update-step-version-choice-save-form is in ERROR 500 

https://github.com/user-attachments/assets/9b569698-18c7-416f-8583-857555d82c41

This topic has to be discussed with @gericfo.

File: classes/Upgrader.php [hunk 13]
```diff
@@ -121,17 +126,26 @@ public function getDestinationVersion(): ?string
...
-        return $channelFile->autoupgrade->last_version;
+        $destinationVersion = $this->getDestinationVersion();
+
+        $eligibleAutoupgradeReleases = array_filter($autoupgradeReleases, function ($autoupgradeRelease) use ($destinationVersion) {
+            return $autoupgradeRelease->getPrestashopMinVersion() <= $destinationVersion && $autoupgradeRelease->getPrestashopMaxVersion() >= $destinationVersion;
+        });
+
+        $autoupgradeRelease = reset($eligibleAutoupgradeReleases);
+
+        return $autoupgradeRelease ? $autoupgradeRelease->getRecommendedVersion() : '';
```
Comment (Quetzacoalt91) [inline classes/Upgrader.php:148]: Any reason to use an empty string instead of `null`?

**Review by Quetzacoalt91 — APPROVED** [review]

File: classes/Upgrader.php (hunk 13 above)
Comment (ga-devfront) [reply classes/Upgrader.php:148]: I return an empty string so as not to alter the management of the `classes/UpgradeSelfCheck.php` cache.

**Review by ingridusta — APPROVED** [review]
Hello @ga-devfront, 

QA Note about the error 500 instead of warning in check requirements while trying to update to v9.x is well fixed and tested : 

- Via UI : 
Capture d’écran 2025-05-06 à 16 44 16
- Via CLI : 
Capture d’écran 2025-05-06 à 18 16 29


---


For this pr, here are listed all the tests that had been run : 

**VIA UI :** 
- from 1.7.4.2-7.1-fpm-alpine-nginx 
- from 1.7.4.4-nginx php 7.1.33
- from 8.0.5-debian-nginx php 8.1.31
- from 1.7.6.0-alpine-nginx php 7.2.34
- from 1.7.0.6-7.1-fpm-alpine-nginx
- from 8.0.4-alpine-nginx php 8.1.31
- from 8.1.2-8.1-fpm-alpine-nginx
- from 1.7.8.5-7.4-fpm-alpine-nginx

**VIA CLI :** 

- 1.7.7.0-7.3-fpm-alpine-nginx 

to the good ps version according to https://api.prestashop-project.org/prestashop

Only for the 1.7.4 shops, the upgrade did not work because of this [pr 38574](https://github.com/PrestaShop/PrestaShop/issues/38574).

Anyway, it's QA approved ✅ !
