### PR TITLE
Handle manually the creation of symlinks while creating a ZIP archive

### LINKED ISSUE #38493: Autoupgrade - Local V9 - Can't create a backup or update after a rollback from 9.0.0
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to do an upgrade after a rollback from the v9, I can't create a backup or do an upgrade after that as you can see : 

https://github.com/user-attachments/assets/859e2c7e-af07-4d02-bb4d-14a59b7b9af4

### Expected behavior

I expect I can do a backup or an upgrade after my rollback 

### Steps to reproduce

1. Install a fresh 8.0.3 with php 8.1 
2. Install Autoupgrade dev version 
3. Do an upgrade to v9 beta1 build4
4. Do a rollback to V8.0.3 
5. Click on Update assistant 
6. Click on Update your store 
7. Click on Get Started
8. Select online channel
9. Click on Next 
10. Click on Next again 
11. Launch Backup 
12. :x: you should have an error during the backup 

### PrestaShop version(s) where the bug happened

8.0.x to V9

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Autoupgrade version dev

### Your company or customer's name goes here (if applicable).

Prestashop

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Now that we have handled symlinks while upgrading PrestaShop, it appears we now have to handle them on backup and restore.
| Type?             | improvement
| BC breaks?        | Nope
| Deprecations?     | Nope
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/38493
| Sponsor company   | @PrestaShopCorp
| How to test?      | Making a backup and restoring a store with symlinks does not fail, and the extraction of a new release of PrestaShop with symlinks (i.e 9.0.0) still works.<ul><li>Update to PrestaShop v9 (from any version of PrestaShop). The update must succeed and a symbolic link `admin-dev/bundles/apiplatform` must exist.</li><li>Make a backup of a store running v9, try updating to a fake PrestaShop v.9.1. The process must succeed.</li><li>Restore to PrestaShop v9, The process must succeed.</li><li>Delete the symbolic link created by PrestaShop (`admin-dev/bundles/apiplatform`), then restore again to PrestaShop v9. It must be restored by the process.</li></ul>

## Roadmap:

- [x] Create a test suite to completely test the management of symlinks in ZIP archives
- [x] Handle symlinks on backup
- [x] Handle symlinks on restore
- [x] Improve previously merged https://github.com/PrestaShop/autoupgrade/pull/1187 with management of symlinks on update.

### CODE REVIEW

File: classes/Task/Update/UpdateFiles.php [hunk 1]
```diff
@@ -133,12 +119,29 @@ protected function upgradeThisFile($orig): bool
...
+                ? $this->container->getFileSystem()->makePathRelative(readlink($orig), pathinfo($orig, PATHINFO_DIRNAME))
+                : $rawSymlink;
+
+            if ($this->container->getFileSystem()->exists($dest)) {
+                $this->container->getFileSystem()->remove($dest);
+            }
+
+            try {
+                $this->container->getFileSystem()->symlink($symLinkTarget, $dest);
+                $this->logger->debug($this->translator->trans('Created link %s to %s.', [$file, $symLinkTarget]));
```
Comment (M0rgan01) [inline classes/Task/Update/UpdateFiles.php:134]:
```suggestion
                $this->logger->debug($this->translator->trans('Created symbolic link %s to %s.', [$file, $symLinkTarget]));
```

File: classes/Task/Update/UpdateFiles.php [hunk 2]
```diff
@@ -133,12 +119,29 @@ protected function upgradeThisFile($orig): bool
...
+
+                return true;
+            } catch (IOException $e) {
+                $this->next = TaskName::TASK_ERROR;
+                $this->logger->error($this->translator->trans('Error while creating link %s: %s', [$file, $e->getMessage()]));
```
Comment (M0rgan01) [inline classes/Task/Update/UpdateFiles.php:139]:
```suggestion
                $this->logger->error($this->translator->trans('Error while creating symbolic link %s: %s', [$file, $e->getMessage()]));
```

File: classes/Task/Update/UpdateFiles.php [hunk 3]
```diff
@@ -115,11 +100,12 @@ public function run(): int
      *
      * @throws Exception
      */
-    protected function upgradeThisFile($orig): bool
+    public function upgradeThisFile($orig): bool
```
Comment (M0rgan01) [inline classes/Task/Update/UpdateFiles.php]: Do we really need to go through the method in public here?

File: classes/Task/Update/UpdateFiles.php [hunk 4]
```diff
@@ -133,12 +119,29 @@ protected function upgradeThisFile($orig): bool
...
+        if (is_link($orig)) {
+            $rawSymlink = readlink($orig);
+            // Windows resolves the symlink target to an absolute path. We restore the original path.
+            $symLinkTarget = $this->container->getFileSystem()->isAbsolutePath($rawSymlink)
+                ? $this->container->getFileSystem()->makePathRelative(readlink($orig), pathinfo($orig, PATHINFO_DIRNAME))
+                : $rawSymlink;
+
+            if ($this->container->getFileSystem()->exists($dest)) {
+                $this->container->getFileSystem()->remove($dest);
+            }
```
Comment (M0rgan01) [inline classes/Task/Update/UpdateFiles.php]: the remove method can also throw an IoException, it might be worth putting it in the try catch

File: classes/Task/Update/UpdateFiles.php [hunk 5]
```diff
@@ -133,12 +119,29 @@ protected function upgradeThisFile($orig): bool
...
-         * Note about symlinks: This is the place where we expected to handle symbolic links.
-         * Unfortunately, PHP does not extract them properly from the archive (see https://bugs.php.net/bug.php?id=46013).
-         * They will be handled in a dedicated backlog by relying on the XML files instead.
-         */
-        if (is_dir($orig)) {
+        if (is_link($orig)) {
+            $rawSymlink = readlink($orig);
+            // Windows resolves the symlink target to an absolute path. We restore the original path.
+            $symLinkTarget = $this->container->getFileSystem()->isAbsolutePath($rawSymlink)
+                ? $this->container->getFileSystem()->makePathRelative(readlink($orig), pathinfo($orig, PATHINFO_DIRNAME))
```
Comment (M0rgan01) [inline classes/Task/Update/UpdateFiles.php]:
```suggestion
                ? $this->container->getFileSystem()->makePathRelative($rawSymlink, pathinfo($orig, PATHINFO_DIRNAME))
```

File: classes/ZipAction.php [hunk 6]
```diff
@@ -289,4 +332,9 @@ public function extractFileFromArchive(ZipArchive $zip, string $fileName): strin
         }
         throw new ZipActionException("Unable to find $fileName file");
     }
+
+    public function isCompressedFileASymLink(int $stat, string $file): bool
+    {
+        return (($stat >> 16) & 0120000) === 0120000 && !in_array(substr($file, -1), ['/', '\\']);
```
Comment (M0rgan01) [inline classes/ZipAction.php:370]: It would be good to have these value ​​as constants (0120000), this would also allow for a short description of the variable name.

File: classes/ZipAction.php [hunk 7]
```diff
@@ -165,14 +183,39 @@ public function extract(string $from_file, string $to_dir): bool
         }
 
         for ($i = 0; $i < $zip->numFiles; ++$i) {
-            if (!$zip->extractTo($to_dir, [$zip->getNameIndex($i)])) {
+            $nameIndex = $zip->getNameIndex($i);
+            $zip->getExternalAttributesName($nameIndex, $opsys, $stat);
```
Comment (M0rgan01) [inline classes/ZipAction.php:187]: This function returns a boolean, we could examine it to see if the operation went well

File: classes/ZipAction.php [hunk 8]
```diff
@@ -165,14 +183,39 @@ public function extract(string $from_file, string $to_dir): bool
...
+                            [
+                                '%file%' => $nameIndex,
+                                '%error%' => $e->getMessage(),
+                            ]
+                        )
+                    );
+                    $zip->close();
+
+                    return false;
+                }
```
Comment (M0rgan01) [inline classes/ZipAction.php]: we raise an error log on the Task side if the operation fails, so we could instead use a warning log here
```suggestion
                    $this->logger->warning(
                        $this->translator->trans(
                            'Could not extract symbolic link %file% from archive: %error%',
                            [
                                '%file%' => $nameIndex,
                                '%error%' => $e->getMessage(),
                            ]
                        )
                    );
                    $zip->close();

                    return false;
                }
```

File: classes/Task/Update/UpdateFiles.php [hunk 9]
```diff
@@ -59,39 +59,24 @@ public function run(): int
...
-                /** @var array{'name':string,'target':string} */
-                $symlink = $symlinksToUpdate->getNext();
-                if (!$this->updateThisSymbolicLink($symlink['name'], $symlink['target'])) {
-                    $this->next = TaskName::TASK_ERROR;
-                    $this->logger->error($this->translator->trans('Error when trying to update link %s.', [$symlink['name']]));
-                    break;
-                }
+            // Note - upgrade this file means do whatever is needed for that file to be in the final state, delete included.
+            if (!$this->upgradeThisFile($file)) {
+                // put the file back to the begin of the list
```
Comment (M0rgan01) [inline classes/Task/Update/UpdateFiles.php]: Should this comment be removed?

File: classes/Task/Update/UpdateFiles.php (hunk 3 above)
Comment (Quetzacoalt91) [reply classes/Task/Update/UpdateFiles.php]: Nope, these are the remains of a temporary test I've made

File: classes/Task/Update/UpdateFiles.php (hunk 1 above)
Comment (Quetzacoalt91) [reply classes/Task/Update/UpdateFiles.php:134]: I've chosen not to be too technical on the logs

File: classes/Task/Update/UpdateFiles.php (hunk 4 above)
Comment (Quetzacoalt91) [reply classes/Task/Update/UpdateFiles.php]: Good idea

File: classes/Task/Update/UpdateFiles.php (hunk 1 above)
Comment (M0rgan01) [reply classes/Task/Update/UpdateFiles.php:134]: I understand, so we need to change the log in ZipAction `Could not extract symbolic link %file% from archive: %error%`

File: classes/ZipAction.php (hunk 7 above)
Comment (Quetzacoalt91) [reply classes/ZipAction.php:187]: The values of `$opsys` and `$stat` will also be set depending on the successfulness of the method, so it should already be fine.

Comment (M0rgan01) [reply classes/ZipAction.php:187]: :thinking: ok there are pointers

File: classes/ZipAction.php (hunk 8 above)
Comment (Quetzacoalt91) [reply classes/ZipAction.php]: I will update this according to the changes of https://github.com/PrestaShop/autoupgrade/pull/1333

File: classes/ZipAction.php (hunk 7 above)
Comment (Quetzacoalt91) [reply classes/ZipAction.php:187]: yes, they are sent by reference

File: classes/ZipAction.php (hunk 6 above)
Comment (Quetzacoalt91) [reply classes/ZipAction.php:370]: I had some links to the related documentation about this, I'm moving the related PHP doc block close to this value.

**Review by M0rgan01 — DISMISSED** [review]

**Review by ga-devfront — APPROVED** [review]

**Review by ingridusta — APPROVED** [review]
Hello @Quetzacoalt91,

- Update from 8.0.5-debian-nginx (php8.1.31) to PrestaShop v9 (via local archives) : Update succeeded and the symbolic link admin-dev/bundles/apiplatform exists ✅ 
- Backup + update to fake 9.1.0 (symlink deleted between backup and update) : Backup succeeded, update succeeded and the symbolic link admin-dev/bundles/apiplatform exists ✅ 
- Restore to v9 (symlink deleted before restore) : restore succeeded and the symbolic link admin-dev/bundles/apiplatform exists ✅ 
- Restore to v8 (symlink not deleted) : restore succeeded but the symlink is not deleted (an issue will be opened but it does not concern this ticket)

QA approved ✅
