### PR TITLE
Run command "assets:install" during the update process for PS 9.0.1

### LINKED ISSUE #38892: Update Assistant Failed update from 8.2.1 to 9.0.0
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Update Assistant failing at the extraction phase:

Could not extract link admin/bundles/apiplatform from archive: Failed to create "symbolic" link from "../../vendor/api-platform/core/src/Symfony/Bundle/Resources/public/" to "/home2/xxxxxxx/public_html/ps90test/**admin_folder**/autoupgrade/tmp/files/admin/bundles/apiplatform".

There's no further description to the error, so I can't tell if it's an update issue or server permission issue or what.  

### Expected behavior

Extraction should work

### Steps to reproduce

Use update assistant 7.1 to try to update shop from 8.2.1 to 9.0.0

### PrestaShop version(s) where the bug happened

8.2.1 to 9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### LINKED ISSUE #38960: AutoUpgrade module v7.1.1 cannot perform the update because the PHP symlink function is disabled or unavailable.
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When attempting to upgrade from PrestaShop 1.7.8.0 to 8.2.1 using the AutoUpgrade module v7.1.1, I encounter the following error:
"Je třeba povolit následující funkce PHP: symlink" (which translates to "You need to enable the following PHP functions: symlink").

As a result, the "Next" button is disabled, and the upgrade cannot proceed.

However, the symlink function is disabled on the vast majority of shared hosting environments (approx. 99%), so it shouldn't be a hard requirement for running the upgrade.

After downgrading AutoUpgrade to version 7.1.0, I was able to perform the upgrade successfully. However, with version 7.1.1, the upgrade fails.

Image

### Expected behavior

Upgrade will works without symlink

### Steps to reproduce

1) install PS 1.7.8.0
2) install autoupgrade 7.1.1
3) try to update

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

autoupgrade v7.1.1

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Prepare Update Assistant to be compliant with PS 9.0.1. It replaces the management of symlink inside the archive with the command "assets:install".
| Type?             | new feature
| BC breaks?        | Nope
| Deprecations?     | Nope
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/38892, fixes https://github.com/PrestaShop/PrestaShop/issues/38960<br>Related to https://github.com/PrestaShop/PrestaShop/pull/39327
| Sponsor company   | @PrestaShopCorp
| How to test?      | Update can run even if the server does not handle symlinks

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
It appears the code provided by the core triggers an error because of a collision between the versions of Symfony/console included by the Core and Update Assistant. I guess we'll have to switch to a more "containerized" call of this Symfony command.

File: classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php [hunk 1]
```diff
@@ -869,4 +871,34 @@ public function warmupCoreCache(): void
...
+
+        $this->logger->info($this->container->getTranslator()->trans('Installing assets'));
+
+        // Calling PrestaShop\PrestaShop\Adapter\Bundle\AssetsInstaller::installAssets() is impossible at the time of writing of this method.
+        // Attempting to call it from Update Assistant v7 triggers a collision between the versions of the package smyfony/console provided
+        // by the core and Update Assistant. We run a basic exec to avoid it.
+
+        $rootPath = $this->container->getProperty(UpgradeContainer::PS_ROOT_PATH);
+        $adminSubDir = $this->container->getProperty(UpgradeContainer::PS_ADMIN_SUBDIR);
+        $command = 'php ' . $rootPath . '/bin/console assets:install --symlink --no-interaction --env=prod ' . $adminSubDir;
```
Comment (Quetzacoalt91) [inline classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php]: @jolelievre @boherm need your review on the use of the parameter `--symlink`.

**Review by ga-devfront — DISMISSED** [review]

**Review by ingridusta — CHANGES_REQUESTED** [review]
Hey hey hey @Quetzacoalt91, 

It's not in the CA but as this pr should be released before v9.0.1, when the user tries to update to v9.0.0 you should check that the symlink method is enabled. 
We actually have : 
Capture d’écran 2025-09-08 à 11 38 15
QA is still in progress !

**Review by ingridusta — CHANGES_REQUESTED** [review]
Hey again @Quetzacoalt91 👋 , 

While trying to upgrade to v9.0.1 with a local archive (after a successful backup), an error popped : 

error to v9 0 1

No details are listed in logs.

**Review by ga-devfront — APPROVED** [review]

File: classes/UpgradeSelfCheck.php [hunk 2]
```diff
@@ -673,17 +673,24 @@ public function getNotExistsPhpFunctions(): array
...
-                     'chdir', 'chmod', 'symlink',
-                 ] as $function) {
+
+        $neededFunctions = [
+            'fopen', 'fclose', 'fread', 'fwrite', 'rename', 'file_exists', 'unlink', 'rmdir', 'mkdir', 'getcwd',
+            'chdir', 'chmod',
+        ];
+
+        if ($this->destinationVersion === '9.0.0') {
+            $neededFunctions[] = 'symlink';
```
Comment (Hlavtox) [inline classes/UpgradeSelfCheck.php:683]: I thought that the whole point of doing it was to NOT need symlink, or? This will fail if symlink is blocked no?

Comment (Quetzacoalt91) [reply classes/UpgradeSelfCheck.php:683]: Even if we fix that for the upcoming version, 9.0.0 has been published with a symbolic link and we will always have to handle this.
This is valid for anyone trying to use the local channel with a zip file of PrestaShop 9.0.0, and this allow us to publish a new version of this module while the 9.0.1 is being prepared (`9.0.1` being different from `9.0.0`, the requirement will disappear)

Comment (Hlavtox) [reply classes/UpgradeSelfCheck.php:683]: Aaaaaah, yes, so I am missing something. This is targetting precisely 9.0.0, not 9.0.1. :-) Now I understand Thomas, sorry!

Comment (Quetzacoalt91) [reply classes/UpgradeSelfCheck.php:683]: No worries :)

**Review by ingridusta — APPROVED** [review]
Hey hey @Quetzacoalt91, 

### PRECOND : I have the problem with prod version with symlink not handled ✅ 
dev branch symlink


### CASE : Update from 8.2.1 to v9.0.1 with symlink handled - WEB UI ✅ 

https://github.com/user-attachments/assets/8dc89f97-b953-4593-b01a-8ee600c51d68

Back up and update works as expected.


### CASE : Update from 8.2.1 to v9.0.1 with symlink handled - CLI ✅ 

https://github.com/user-attachments/assets/f32e9119-dd58-4326-83c5-6c761c0aaa8a

Back up and update works as expected.

### CASE : Backup from v9.0.0 AND Restore with symlink handled - WEB UI ✅ 

https://github.com/user-attachments/assets/cd80d163-0c05-48b5-8b37-691eb3eb9de2

The symlink is found in the back up and the restore

### CASE : Backup from v9.0.0 AND Restore with symlink handled - WEB UI ✅ 

https://github.com/user-attachments/assets/a8796ecb-de79-45e8-aa27-eec82af8c8e8

The symlink is found in the back up and the restore

### CASE : Back up from v9.0.0 AND Restore with symlink not handled > Error is displayed - WEB UI ✅  

https://github.com/user-attachments/assets/52e9c23c-c40f-4fe4-a8a5-48c97dc570b9

Error is displayed + restore failed as expected 

### CASE : Back up from v9.0.0 AND Restore with symlink not handled > Error is displayed - CLI ✅  

https://github.com/user-attachments/assets/c929599f-eab3-4544-a9da-2be41c3e3f0c

Error is displayed + restore failed as expected  

Also, no regression detected. 

QA approved 🥇
