### PR TITLE
Persist current product route when upgrading to 9.0.0

### LINKED ISSUE #40063: PrestaShop 9: Legacy Category/Product URLs Return 404 With New Default Routing (No Redirects or Fallback)
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

**Intro**

While testing an upgrade from a legacy PrestaShop installation to PrestaShop 9, we encountered a situation we wanted to bring to the PrestaShop developers’ attention.

Note: In our upgrade test, we installed PrestaShop 9.0.1 and migrated legacy shop content without making any changes to SEO & URLs settings. The behavior described below occurs with the default PS9 configuration.

This concerns how PS9 handles product URLs when upgrading from stores that previously used category-based product link structures.

**Summary**

In PrestaShop 9, the default product route removes the {category} token:

/{id}-{rewrite}.html

This new “clean” structure works fine for fresh installs.
However, when upgrading a legacy shop, PS9 does not provide redirects, rewrites, or fallback resolution for older product URLs that include the category segment:

/my-category/{id}-{rewrite}.html

Therefore, any external or indexed legacy URL containing a category will return a 404, unless the merchant manually restores a category-aware route or implements redirects.

### Expected behavior

During upgrade acceptance testing we noticed that /category/product links were 404'ing and after some research found the ps9.0.1 default product route removed category.  We readded the category to product route and external links functioned.  
When I heard of the new feature I assumed/expected that links with category would resolve.  

Thanks in advance for ps team review and hope this contributes in some small way. 

### Steps to reproduce

Steps to Reproduce

1. Install PrestaShop 9.0.1 (fresh installation or upgrade).
2. Leave SEO & URLs at the default PS9 configuration (no category)
3. Create a product or use any demo product included with a fresh install.
4. Assign the product to a category (any category, including the default “Home” or a newly created category).
5. Confirm the new short URL works:

/{id}-{rewrite}.html

6. Now manually construct and request the category-based legacy pattern (even on a fresh PS9 install), for example:

/my-category/{id}-{rewrite}.html

or using the real category slug:

/accessories/12-mountain-bike-helmet.html

7. Observe that the page returns 404 Not Found.
8. No redirect or rewrite is generated by default.
9. Breadcrumb still displays the category hierarchy, even though the URL itself does not include the category segment.

### PrestaShop version(s) where the bug happened

9.0.1 from 1.6.1.4

### How you installed PrestaShop

download 9.0.1 and installed on staging and used migration pro to import shop datas

### PHP version(s) where the bug happened

8.2.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

PrestaHeroes.com

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | If routes have not been modified, they are not in ps_configration. If you upgrade to 9.0.0, your product URLs change and you completely RUIN YOUR SEO. Caused by https://github.com/PrestaShop/PrestaShop/pull/37467.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/40063#issuecomment-3564109485
| Sponsor company   | TRENDO s.r.o.
| How to test?      | Upgrade from 8.2.3 to 9.0.0 and check that your product rewrite rule in SEO settings is the same.

### CODE REVIEW

**Review by M0rgan01 — DISMISSED** [review]

File: upgrade/php/add_product_routes.php [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ *
+ * If the merchant kept the original routes the former urls won't be reachable any
+ * more and SEO will be lost. So we force a custom rule matching the former format.
+ *
+ * If the route was customized, no need to do anything. We don't change anything for
+ * multi shop either since it will be used it the merchant has already changed them.
+ */
+function add_product_routes()
+{
+    Configuration::loadConfiguration();
```
Comment (Quetzacoalt91) [inline upgrade/php/add_product_routes.php]: Why did you need this line?

Comment (Hlavtox) [reply upgrade/php/add_product_routes.php]: I got inspired here - https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/php/add_supplier_manufacturer_routes.php

Honestly, I did not think about it too much, maybe it's not needed indeed

Comment (Quetzacoalt91) [reply upgrade/php/add_product_routes.php]: I'll make some tests then. We need to create a catch-up file as well for merchants who already updated to 9.0.0

Comment (Hlavtox) [reply upgrade/php/add_product_routes.php]: @Quetzacoalt91 I would not make a catchup. If we already broke their SEO rules when upgrading to 9.0.0, they probably fixed it, or Google began to reindex it. If we change it again now, it would be even worse.

Comment (Quetzacoalt91) [reply upgrade/php/add_product_routes.php]: Fair enough, I see another issue with a catch-up file, where someone who installed PS 9.0.0 would potentially see its URLs changing while updating to 9.0.2

File: upgrade/php/add_product_routes.php [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+ * In Prestashop 9.0.0 the default product routes have been modified by removing
+ * category and EAN from the URL.
+ *
+ * If the merchant kept the original routes the former urls won't be reachable any
+ * more and SEO will be lost. So we force a custom rule matching the former format.
+ *
+ * If the route was customized, no need to do anything. We don't change anything for
+ * multi shop either since it will be used it the merchant has already changed them.
+ */
+function add_product_routes()
```
Comment (Quetzacoalt91) [inline upgrade/php/add_product_routes.php]: Can we rename the method and the file name ?

```suggestion
function ps_900_set_previous_product_route_as_custom()
```

**Comment by Hlavtox** [comment]
@Quetzacoalt91 Should be ready. :-)

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @Hlavtox 

Thank you for your PR, I tested it and it seems to works as you can see : 

https://github.com/user-attachments/assets/b612bd83-82ee-4b2d-8a44-af9a72555f06


Tested from : 
8.2.3 to 9.0.1
8.0.4 to 9.0.1

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you
