### PR TITLE
Provide absolute URL to fix routing issues

### LINKED ISSUE #39185: Corrupted module URLs after symfony layout migration of configuration page
### Describe the bug and add attachments

I get the issue on a Prestashop 9 instance deployed from scratch with nginx-1.28/php-fpm-8.4/mariadb-10.11 
I go editing value of customtext module, when I save changes I'm redirected on the 404 error page.
I have no issues in others sections/modules to save my changes.

Here http logs when saving changes in ps_customtext module showing 404 on POST request : 
```
5.14.178.222 - - [23/Jul/2025:14:12:22 +0000] "POST /adminxxxx/improve/modules/manage/action/configure/index.php?controller=AdminModules&configure=ps_customtext&token=00f8.Y5ZirEthpAj3YUiIq1O28zK62N1dLGcI3NNEaQ2u0XU.UKER_AQgnUKnEgzXnTDBx23yvqoVfl55iJstDE_3hzk0xSXnfy6VQ7UuDQ HTTP/1.1" 404 10726 "https://mydomain.fr/adminxxxx/improve/modules/manage/action/configure/ps_customtext?_token=1f769a66f95509f3b52a01a38d.-UjGsNnLjhU9Oue7p_-mkAm5Gwt4R1wOQHe6PzRzGTE.yn-14JaKt19tSaPkkZzRpFbxfXwwFWV_FD_TWnYqT32uG4H77YS_Xn91og" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
5.14.178.222 - - [23/Jul/2025:14:12:23 +0000] "GET /themes/hummingbird/assets/cache/theme-f375a05.css HTTP/1.1" 304 0 "https://mydomain.fr/adminxxxx/improve/modules/manage/action/configure/index.php?controller=AdminModules&configure=ps_customtext&token=00f8.Y5ZirEthpAj3YUiIq1O28zK62N1dLGcI3NNEaQ2u0XU.UKER_AQgnUKnEgzXnTDBx23yvqoVfl55iJstDE_3hzk0xSXnfy6VQ7UuDQ" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
5.14.178.222 - - [23/Jul/2025:14:12:23 +0000] "GET /themes/hummingbird/assets/cache/bottom-1402e05.js HTTP/1.1" 304 0 "https://mydomain.fr/adminxxxx/improve/modules/manage/action/configure/index.php?controller=AdminModules&configure=ps_customtext&token=00f8.Y5ZirEthpAj3YUiIq1O28zK62N1dLGcI3NNEaQ2u0XU.UKER_AQgnUKnEgzXnTDBx23yvqoVfl55iJstDE_3hzk0xSXnfy6VQ7UuDQ" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
5.14.178.222 - - [23/Jul/2025:14:12:23 +0000] "GET /module/blockwishlist/action?action=getAllWishlist HTTP/1.1" 200 90 "https://mydomain.fr/adminxxxx/improve/modules/manage/action/configure/index.php?controller=AdminModules&configure=ps_customtext&token=00f8.Y5ZirEthpAj3YUiIq1O28zK62N1dLGcI3NNEaQ2u0XU.UKER_AQgnUKnEgzXnTDBx23yvqoVfl55iJstDE_3hzk0xSXnfy6VQ7UuDQ" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
```
I don't see errors in php logs or nginx errors logs.

### Expected behavior

Text well saved with 200 http response

### Steps to reproduce

1. Go to configure custom text module
2. Update text
3. Save

### PrestaShop version(s) where the bug happened

9.0.0

### How you installed PrestaShop

Downloading package on prestashop home page

### PHP version(s) where the bug happened

8.4

### If your bug is related to a module, specify its name and its version

ps_customtext v4.2.1

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Provide absolute URL to fix routing issues. Fixes potential issues coming from relative URLs not being reliable after symfony migration. See https://github.com/PrestaShop/PrestaShop/issues/39185. cc @Touxten 
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/39185
| Sponsor company   | TRENDO s.r.o.
| How to test?      | Just test the module can be configured correctly and loads in the backoffice, so we didn't break anything or have some typo. (On nginx server, this could be problematic.)

### CODE REVIEW

**Comment by Touxten** [comment]
@Hlavtox 
Add use **ngnix** in the how to test i also have to update my how to test

**Comment by Hlavtox** [comment]
@Quetzacoalt91 Ping Thomas, this is some unrelated fault I guess?

File: controllers/admin/AdminSelfUpgradeController.php [hunk 1]
```diff
@@ -236,7 +234,7 @@ public function init()
                 // delete the potential xml files we saved in config/xml (from last release and from current)
                 $upgrader->clearXmlMd5File($this->upgradeContainer->getProperty(UpgradeContainer::PS_VERSION));
                 $upgrader->clearXmlMd5File($upgrader->getDestinationVersion());
-                Tools14::redirectAdmin(self::$currentIndex . '&conf=5&token=' . Tools14::getValue('token'));
+                Tools14::redirectAdmin($this->context->link->getAdminLink('AdminSelfUpgrade', false) . '&conf=5&token=' . Tools14::getValue('token'));
```
Comment (Quetzacoalt91) [inline controllers/admin/AdminSelfUpgradeController.php]: Actually this whole block can be deleted, the action `refreshCurrentVersion` is not anymore sent.

It has disappeared on v7 with the rework of the UI, can you please delete the lines from l. 223 to 238?

**Comment by Quetzacoalt91** [comment]
The tests of 7.3.0 have already started, I flag this PR for the next version that will be 7.4.0.

**Comment by Hlavtox** [comment]
@Quetzacoalt91 Thomas, like this it's OK?

**Review by Quetzacoalt91 — APPROVED** [review]
Perfect, thanks @Hlavtox

**Comment by ShaiMagal** [comment]
@Quetzacoalt91 Hello, can this be merged?

**Comment by Quetzacoalt91** [comment]
Not yet @ShaiMagal, I'm waiting the tests of 7.3.0 to complete so I can release the version. Then there is a scenario I want to check with the QA team about a double `index.php` appearing in the URL when we use the module. I'd to check if the PR solves this issue at the same time we look for regressions.

**Review by AureRita — APPROVED** [review]
Hi @Hlavtox 

Thank you for your PR, I tested it and it seems to works as you can see : 

https://github.com/user-attachments/assets/afad22f7-5054-40b7-b35b-964fcd411d10

Tested from : 
8.0.4 to 8.1.1
8.1.1 to 8.1.5
8.1.5 to 8.2.0
8.2.0 to 9.0.0
8.0.4 to 9.0.0

FYI : this PR doesn't correct the issue of double index as we can see : 

https://github.com/user-attachments/assets/809a6d12-1f04-41fc-9d35-dfbeb492866e


Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by Hlavtox** [comment]
@AureRita You are testing absolutely unrelated things, but if it's already merged, what can we do :D
