### PR TITLE
[FIX] Issue: is not possible to go online then we have local archive

### LINKED ISSUE #37909: Autoupgrade - New UI - Can't go on a minor/major version when you have local file
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you want to do an upgrade to minor/major version and you have some files on your folder download, it 'll not allow you to clic on the next step as you can see : 

https://github.com/user-attachments/assets/dbfabed1-83d3-4466-b1ea-63088bbbda78

### Expected behavior

I wish I could update to major/minor version when I have some files on download 

### Steps to reproduce

1. Install a 8.0.4 
2. Install the new version of Autoupgrade
3. Go to update assistant 
4. Put some zip/archive in your [yourShopFolder]/admin-dev/autoupgrade/download
5. Clic on Update your store and Next
6. Select Your minor/major version 
7. Clic on Next 
8. :x: You should have an error in your console 

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

AutoupgradeV7

### Your company or customer's name goes here (if applicable).

Prestashop

### PR DESCRIPTION
**Pull request by ga-devfront**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix the issue then you try to select online channel but you got local archive (cf issue).
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/37909
| Sponsor company   | @PrestaShopCorp
| How to test?      | Try to reproduce bug in the issue.

### CODE REVIEW

File: _dev/src/ts/pages/UpdatePageVersionChoice.ts [hunk 1]
```diff
@@ -90,6 +90,11 @@ export default class UpdatePageVersionChoice extends StepPage {
   };
 
   #saveForm = async () => {
+    api.currentRequestAbortController?.abort();
```
Comment (Quetzacoalt91) [inline _dev/src/ts/pages/UpdatePageVersionChoice.ts]: What do you think about introducing a new method?

```suggestion
    api.abortCurrentCall();
```

**Review by tblivet — DISMISSED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @ga-devfront,


I tested your  PR and I found some bugs : 

804 to 820 : 
https://github.com/user-attachments/assets/6e2bbdd5-5143-4bd6-9f2a-944cabe0f248
Update OK but my local version of prestashop (.zip and .XML on the download folder) are deleted.


812 to 820 : 
https://github.com/user-attachments/assets/a1914dba-1e6b-4bb2-bf6a-554ea59d1cc1
Update KO. Can't update the database

Can you check that please?

Thanks for your feedback!

**Comment by ga-devfront** [comment]
@paulnoelcholot 

> 804 to 820 :
https://github.com/user-attachments/assets/6e2bbdd5-5143-4bd6-9f2a-944cabe0f248
Update OK but my local version of prestashop (.zip and .XML on the download folder) are deleted.

The first bug is already known to our service, this behavior has always been present but the fix is ​​not prioritized at the moment.

> 812 to 820 :
https://github.com/user-attachments/assets/a1914dba-1e6b-4bb2-bf6a-554ea59d1cc1
Update KO. Can't update the database

For this I actually see the problem, it is the local channel that you have configured that is taken into account and not the online one. You should open a Jira bug ticket or a GitHub issue.

Thanks for the feedback, however in any case the 2 problems do not occur because of my fix. The problems are at another level and deserve dedicated tickets and PR.

**Comment by paulnoelcholot** [comment]
So it's good for me! :tada: 
Thanks! 

https://github.com/user-attachments/assets/8e4be97c-0ec5-422c-aadc-bdbe13e2cfa3

**Review by paulnoelcholot — APPROVED** [review]

**Review by paulnoelcholot — APPROVED** [review]
