### PR TITLE
[FIX] save iso for translations

### LINKED ISSUE #38110: autoupgrade translations not working
### Describe the bug and add attachments

I have no idea why, but the translations seem to be broken in some parts of the module.

**They work on the initial page**

Image

**But not on the second one**

Image

Ping @Quetzacoalt91 @M0rgan01 

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v7.0.0-dev.4

### PR DESCRIPTION
**Pull request by ga-devfront**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Translations fix https://github.com/PrestaShop/PrestaShop/issues/38110
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fix https://github.com/PrestaShop/PrestaShop/issues/38110
| Sponsor company   | @PrestaShopCorp
| How to test?      | Try reproduce issue in ticket. Make sure all translations are available on translation fail from your language before reporting another issue.

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

File: classes/UpgradeContainer.php [hunk 1]
```diff
@@ -651,11 +655,19 @@ public function getTranslator(): Translator
...
             // @phpstan-ignore booleanAnd.rightAlwaysTrue (If PrestaShop core is not instantiated properly, do not try to translate)
             if (method_exists('\Context', 'getContext') && \Context::getContext()->language) {
-                $locale = \Context::getContext()->language->iso_code;
+                $newConfiguration = [
+                    LanguageConfiguration::ISO_LANGUAGES => \Context::getContext()->language->iso_code,
+                ];
+
+                $languageConfiguration->merge($newConfiguration);
+                $this->configurationStorage->save($languageConfiguration);
             }
```
Comment (M0rgan01) [inline classes/UpgradeContainer.php:667]: maybe we want to add a condition to know if the configuration already exists? to avoid a multitude of configuration updates during the process

File: classes/Parameters/UpgradeFileNames.php [hunk 2]
```diff
@@ -46,6 +46,8 @@ class UpgradeFileNames
 
     const RESTORE_CONFIG_FILENAME = 'restore_config.var';
 
+    const LANGUAGE_CONFIG_FILENAME = 'language_config.var';
```
Comment (M0rgan01) [inline classes/Parameters/UpgradeFileNames.php:49]: do we want to clean this file after a process? like we do with others

**Comment by paulnoelcholot** [comment]
Hello @ga-devfront,

I tested your PR and it's good for me! :tada: 

Thanks! 

image

**Review by paulnoelcholot — APPROVED** [review]

**Comment by ga-devfront** [comment]
After reflection I think that the solution is not totally viable because we are basing ourselves on a single language for all users but potentially 2 users with different languages ​​can access the module pages at the same time which can cause a translation problem.
I think I implemented the saving of an associative array: user_id => iso
